// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Company struct {
	ID   string `json:"id"`
	Name string `json:"name"`
	Loc  string `json:"loc"`
	Sal  string `json:"sal"`
}

type Job struct {
	ID           string `json:"id"`
	Cid          string `json:"cid"`
	Jobname      string `json:"jobname"`
	Salary       string `json:"salary"`
	Noticeperiod string `json:"noticeperiod"`
}

type NewCompany struct {
	Name string `json:"name"`
	Loc  string `json:"loc"`
	Sal  string `json:"sal"`
}

type NewJob struct {
	Cid          string `json:"cid"`
	Jobname      string `json:"jobname"`
	Salary       string `json:"salary"`
	Noticeperiod string `json:"noticeperiod"`
}

type NewUser struct {
	Username string `json:"username"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type User struct {
	ID        string `json:"id"`
	Username  string `json:"username"`
	Email     string `json:"email"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
	DeletedAt string `json:"deleted_at"`
}
